/**
 * AZSCO Assistant — server-side proxy for the Gemini API.
 *
 * The API key lives here, in the GEMINI_API_KEY environment variable, and never
 * reaches the browser. The static site posts {lang, messages} to this endpoint.
 *
 * Deploy target: any host that runs a Node serverless function with the Web
 * Request/Response API (Vercel, Netlify Functions v2, Deno Deploy). The
 * Cloudflare Workers variant in backend/workers/chat-worker.js is the one this
 * site actually runs, and it also carries the contact form's /contact route;
 * this file is the chat half alone, for a host where Workers is not an option.
 *
 * Environment variables:
 *   GEMINI_API_KEY  required; your key from https://aistudio.google.com/apikey
 *                   (no payment method needed for the free tier)
 *   ALLOWED_ORIGIN  strongly recommended; comma-separated origins allowed to
 *                   call this endpoint. Requests from anywhere else are refused
 *                   before Gemini is called. Unset means anyone may call it and
 *                   spend the quota.
 *   GEMINI_MODEL    optional; defaults to DEFAULT_MODEL below.
 *
 * The prompt block below is generated. Edit CHAT_FACTS / CHAT_RULES in
 * tools/build.py and run `python3 tools/build.py`, which rewrites it here and in
 * backend/workers/chat-worker.js, then redeploy. Editing it by hand means the
 * next build silently reverts the change.
 *
 * Why Gemini and not Mistral: Mistral's free tier rate-limits far too
 * aggressively for live visitor traffic (a single test message could exhaust
 * it). Google AI Studio's free tier suits light, ongoing production use --
 * see https://ai.google.dev/gemini-api/docs/models for current limits.
 */

const DEFAULT_MODEL = 'gemini-2.5-flash';

const MAX_CHARS = 1000;     // per message
const MAX_MESSAGES = 40;    // per request
const MAX_TOKENS = 500;     // per reply
const BODY_LIMIT = 100_000; // bytes of request body we will read at all

/* AZSCO-PROMPT:BEGIN -- generated by tools/build.py. Do not edit by hand:
   edit CHAT_FACTS / CHAT_RULES in tools/build.py and rebuild. */
const FACTS = `
COMPANY
- AZSCO Security Services Company (formerly Almail Zone Security Services),
  established 2014, headquartered in Qibla, Kuwait.
- Office: Floor 27B, Kuwait Building Tower, Fahad Al Salem St., Qibla, Kuwait.
- Telephone: (+965) 1808606.
- Email: info@azsco.com for general enquiries, sales@azsco.com for sales
  and quotations.
- Office hours: Sunday to Thursday, 8:30-16:30. Emergency response 24/7.
- CEO: Dr. Abdulaziz Almail.
- Certified ISO 9001:2015 for quality management, and compliant with
  Anti-Money Laundering standards.

WHAT AZSCO DOES
AZSCO provides security manpower and security systems. Services:
- Facility Guarding: trained, uniformed officers guarding apartments, malls,
  banks, stores, offices, compounds, industrial sites and events.
- VIP Protection & Rapid Intervention: physically and technically qualified
  personal guards for individuals needing a high level of security, plus
  rapid-intervention response to critical sites.
- Central Operations Room: a 24/7 monitoring and communications room that
  keeps continuous contact with every AZSCO-guarded site and dispatches a
  rapid response to any incident.
- Security Patrols: scheduled patrols by trained officers equipped with the
  necessary tools, reinforcing the security of guarded sites and areas.
- Security Systems: advanced, site-specific systems -- surveillance cameras
  and fire and theft alarm systems -- installed and monitored by AZSCO, with
  alerts routed to the Central Operations Room for rapid patrol intervention.

OTHER FACTS
- Officers are screened, licensed, uniformed, trained (first aid,
  fire-fighting, dealing with the public, dealing with accidents,
  self-defense) and supervised.
- Officers come from a range of nationalities: Kuwaiti, Indian, Egyptian,
  Chadian, Nigerian, Nepalese and stateless individuals.
- Serves government, commercial, financial, industrial, residential and many
  other sectors across Kuwait.
- Technology partners whose equipment powers AZSCO's Security Systems service
  and Central Operations Room monitoring: Ajax, Rasilient, Avigilon,
  Teltonika, Inrico, Hikvision, Pelco and Motorola.
- Clients include Radisson Blu Hotel Kuwait, Millennium Hotels and Resorts,
  Kuwait Ports Authority, Alghanim Industries and Alnasser, among others --
  see the Clients page for more.
- A free site survey is the normal first step for a new enquiry.
`;

const RULES = `
RULES
- Answer ONLY questions about AZSCO, its security services, and how to get in
  touch. For anything else, politely say it is outside what you can help with
  and offer to put the visitor in touch with the team.
- Use ONLY the facts above. If you do not know something - pricing, guard
  numbers, availability, contract terms, staff names - say so plainly and point
  the visitor to (+965) 1808606 or info@azsco.com. Never guess or invent.
- Never quote a price, promise a response time, or commit AZSCO to anything.
- Be brief: two or three short paragraphs at most. Plain text, no markdown
  headings or bullet lists.
- If a visitor appears to have an urgent security incident, tell them to call
  (+965) 1808606 immediately rather than continuing to chat.
`;

function systemPrompt(lang) {
  return `You are the AZSCO Assistant, the virtual assistant on the website of AZSCO,
a security company in Kuwait.
${FACTS}${RULES}- ${lang === 'ar'
      ? 'Reply in Arabic (Modern Standard Arabic), in a professional tone.'
      : 'Reply in English, in a professional tone.'}`;
}
/* AZSCO-PROMPT:END */

function corsHeaders(origin, allowed) {
  return {
    // Echo only an origin we actually allow, so a cached response can never
    // hand one site's permission to another. Vary keeps caches honest about
    // this header changing per request.
    'Access-Control-Allow-Origin': allowed ? origin : 'null',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Max-Age': '86400',
    'Vary': 'Origin',
    'Content-Type': 'application/json',
  };
}

function json(body, status, ctx) {
  return new Response(JSON.stringify(body), {
    status,
    headers: corsHeaders(ctx.origin, ctx.allowed),
  });
}

/* Best-effort per-IP limit. State is per-instance and lost when the instance
   is recycled, so it will not stop a distributed flood -- it stops the
   realistic one: a single script hammering the endpoint and burning a
   free-tier quota the whole site depends on. */
const hits = new Map();

function rateLimited(key, limit, windowMs) {
  const now = Date.now();
  const recent = (hits.get(key) || []).filter(ts => now - ts < windowMs);
  recent.push(now);
  hits.set(key, recent);
  if (hits.size > 5000) {
    for (const [k, stamps] of hits) {
      if (!stamps.length || now - stamps[stamps.length - 1] > windowMs) hits.delete(k);
    }
  }
  return recent.length > limit;
}

async function readJson(request) {
  const declared = Number(request.headers.get('content-length') || 0);
  if (declared > BODY_LIMIT) return null;
  try {
    const text = await request.text();
    if (text.length > BODY_LIMIT) return null;
    const parsed = JSON.parse(text);
    return parsed && typeof parsed === 'object' ? parsed : null;
  } catch {
    return null;
  }
}

export default async function handler(request) {
  const origin = request.headers.get('origin');
  const list = (process.env.ALLOWED_ORIGIN || '').split(',').map(s => s.trim()).filter(Boolean);
  // Unset means "allow anything", which keeps a fresh deployment working before
  // the variable is configured. Once set, it is enforced here rather than left
  // to the browser: CORS only makes a browser discard a response this function
  // has already paid for, and curl ignores it completely.
  const allowed = !list.length || (!!origin && list.includes(origin));
  const ctx = {
    origin: origin || '*',
    allowed,
    ip: request.headers.get('x-forwarded-for') || request.headers.get('cf-connecting-ip') || 'unknown',
  };

  if (request.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: corsHeaders(ctx.origin, allowed) });
  }
  if (!allowed) {
    console.warn('Blocked origin', origin);
    return json({ error: 'Forbidden' }, 403, ctx);
  }
  if (request.method !== 'POST') {
    return json({ error: 'Method not allowed' }, 405, ctx);
  }
  if (!process.env.GEMINI_API_KEY) {
    // Configuration problem, not the visitor's fault — do not leak details.
    console.error('GEMINI_API_KEY is not set');
    return json({ error: 'Assistant unavailable' }, 503, ctx);
  }
  if (rateLimited('chat:' + ctx.ip, 12, 60 * 1000)) {
    return json({ error: 'Too many requests' }, 429, ctx);
  }

  const payload = await readJson(request);
  if (!payload) return json({ error: 'Invalid JSON' }, 400, ctx);

  const lang = payload.lang === 'ar' ? 'ar' : 'en';
  const incoming = Array.isArray(payload.messages) ? payload.messages : [];
  if (!incoming.length) return json({ error: 'No messages' }, 400, ctx);

  // Accept only the shape we expect; drop anything else the client sent.
  // Gemini says "model" where the client says "assistant" -- translate the
  // roles and wrap each turn's text in "parts".
  const contents = incoming
    .slice(-MAX_MESSAGES)
    .filter(m => m && (m.role === 'user' || m.role === 'assistant') && typeof m.content === 'string')
    .map(m => ({
      role: m.role === 'assistant' ? 'model' : 'user',
      parts: [{ text: m.content.slice(0, MAX_CHARS) }],
    }));

  if (!contents.length) return json({ error: 'No usable messages' }, 400, ctx);

  const model = process.env.GEMINI_MODEL || DEFAULT_MODEL;
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`;

  try {
    const res = await fetch(url, {
      method: 'POST',
      headers: {
        'x-goog-api-key': process.env.GEMINI_API_KEY,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents,
        systemInstruction: { parts: [{ text: systemPrompt(lang) }] },
        generationConfig: { temperature: 0.3, maxOutputTokens: MAX_TOKENS },
      }),
    });

    if (!res.ok) {
      console.error('Gemini API error', res.status, (await res.text()).slice(0, 500));
      return json({ error: 'Assistant unavailable' }, 502, ctx);
    }

    const data = await res.json();
    const reply = data?.candidates?.[0]?.content?.parts?.map(p => p.text || '').join('').trim();
    if (!reply) return json({ error: 'Empty reply' }, 502, ctx);

    return json({ reply }, 200, ctx);
  } catch (err) {
    console.error('Proxy failure', err);
    return json({ error: 'Assistant unavailable' }, 502, ctx);
  }
}

export const config = { runtime: 'edge' };
